#!/usr/bin/env bash

QUIET() {
	"${@}" 1>/dev/null
}
FCLEAN() {
	QUIET make fclean
}
MAKE() {
	QUIET make "${@}" -j$(nproc)
}
ERROR() {
	echo -e "\033[0;31m${@}\033[0m" >&2
}
SUCCESS() {
	echo -e "\033[0;32m${@}\033[0m"
}

MEMORY="false"
USAN="false"

while getopts ":mu" opt; do
	case $opt in
		m) MEMORY="true";;
		u) USAN="true";;
		\?) echo "Error: invalid option" >&2; exit 1;;
	esac
done

test_cases=(\
	""\
	"123597875642313546564"\
	"-123597875642313546564"\
	"-1"\
	"0"\
	"0 1"\
	"1 0"\
	"112 80 67"\
	"112 80 67 45"\
	"112 80 67 45 89"\
	"80 78 11267 45 89 9"\
	"80 78 11267 45 89 67 9"\
	"80 2 78 11267 45 89 67 9"\
	"1 80 2 78 11267 45 89 67 9"\
	"5555 987 45 12 321 45 5400 5454 1 654 1231 23"\
	"5555 987 45 12 321 45 987987 5600"\
	"456879 45 1 654 7 65413 4897625 4 6"\
	"1 1 1 1 1 1 1 1"\
	"1 2 3 4 5"\
)

echo "################"
echo "# TEST SORTING #"
echo "################"
FCLEAN && MAKE all
success=0
for i in "${test_cases[@]}"; do
	echo "./PmergeMe ${i}"
	ret=$(./PmergeMe $i)
	echo -e "${ret}"
	# Check if the returned value is actually sorted.
	res=$(echo -e "${ret}" | grep "After" | sed 's/After:\s\+//' | tr ' ' '\n')
	echo "${res}" | sort --general-numeric-sort --check || success=1
done
if [[ "${success}" == 0 ]]; then
	SUCCESS "[ok]"
else
	ERROR "[ko]"
fi


if [[ $MEMORY == "true" ]]; then
	echo "###############"
	echo "# TEST MEMORY #"
	echo "###############"

	success=0
	FCLEAN && MAKE all
	for i in "${test_cases[@]}"; do
		QUIET valgrind --quiet ./PmergeMe $i
	done
	FCLEAN && MAKE asan
	for i in "${test_cases[@]}"; do
		QUIET ./PmergeMe $i
		if [[ $? != 0 ]]; then
			success=1;
		fi
	done
	if [[ "${success}" == 0 ]]; then
		SUCCESS "[ok]"
	else
		ERROR "[ko]"
	fi
fi

if [[ $USAN == "true" ]]; then
	echo "###########################"
	echo "# TEST UNDEFINED BEHAVIOR #"
	echo "###########################"
	FCLEAN && MAKE usan
	for i in "${test_cases[@]}"; do
		QUIET ./PmergeMe $i
	done
fi
